name: pudl
channels:
  - conda-forge
  - defaults
dependencies:
  - pip>=22.0,<23
  - python>=3.10,<3.11
  - python-snappy>=0.6,<7 # Installs the snappy-dev library without using apt
  - sqlite>=3.36,<4
  - numba>=0.56,<0.57
  - catalystcoop.pudl==2022.11.30

  # Jupyter + Dask for interactive computing
  - dask>=2021.8,<2022.11.2
  - dask-gateway>=2022.4,<2022.11
  - dask-labextension>=5.1,<6.1
  - jupyterlab>=3.2,<4.0
  - jupyter-offlinenotebook>=0.2,<0.3
  - jupyter-resource-usage>=0.6,<0.7
  - nbclassic>=0.4,<0.5
  - nbgitpuller>=1.1,<2
  - python-graphviz
  - seaborn>=0.11,<1

  # Install the corresponding PUDL Intake data catalog
  - catalystcoop.pudl_catalog==0.2.0
